using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AbstractLibrary.Data.Models.autoGeneratedContext;
using AbstractLibrary.FormBuilder;
using BigPardakht.Model;
using SignalRMVCChat.Models.autoGeneratedContext;
using TelegramBotsWebApplication;

namespace my_webapp.Model
{

    public class IssueFood:SafeDeleteEntity
    {
        public IssueAssignment IssueAssignment { get; set; }
        public AnimalFoodBuy AnimalFoodBuy { get; set; }
        public long AnimalFoodBuyId { get; set; }
        public long IssueAssignmentId { get; set; }
        
        [Text]
        [Display(Name = "تعداد کیلو برای بز و گوسفند ")]
        public decimal BozQuan { get; set; }
        
        [Text]
        [Display(Name = "تعداد کیلو برای گاو و گاومیش ")]
        public decimal CowQuan { get; set; }

        
        [Text]
        [Display(Name = "قیمت هر کیلو ")]
        public decimal FoodPricePerKg { get; set; }
        
                
        [Text(Help = "قیمت کل نهاده خریداری شده")]
        [Display(Name = "کل مبلغ ")]
        public decimal TotalPrice { get; set; }
        
    }

    public class IssueAssignmentPostViewModel
    {
        [Select]
        [Display(Name = "مشتری ")]
        [Required]
        public long? PersonId { get; set; }
        
        
        [Select]
        [Display(Name = "تعداد گاو و گاومیش ")]
        public double CowCount { get; set; }
        
        [Select]
        [Display(Name = "تعداد گوسفند و بز ")]
        public double BozCount { get; set; }

        public List<IAFoodsViewModel> List { get; set; }
       
        
        [Display(Name = "جمع مبلغ حواله ")]
        public decimal TotalPrice { get; set; }


        [Display(Name = "توضیحات ")]
        public string Description { get; set; }
    }
    public class IAFoodsViewModel
    {
        [Text(Type="number")]
        [Display(Name = "تعداد کیلو برای بز و گوسفند ")]
        [Required]

        public decimal BozQuan { get; set; }
        
        [Text(Type="number")]
        [Display(Name = "تعداد کیلو برای گاو و گاومیش ")]
        [Required]
        public decimal CowQuan { get; set; }
        
        [Hidden]
        [Required]
        public long AnimalFoodId { get; set; }
        
        
        [AbstractLibrary.FormBuilder.ReadOnly]
        [Display(Name = "نهاده ")]
        public string AnimalFoodName { get; set; }
        
        [Text(Help = "کل مبلغی که مشتری می پردازد برای نهاده ای که تحویل می گیرد",Type = "number")]
        [Display(Name = "کل مبلغ ")]
        [Required]
        public decimal TotalPrice { get; set; }

        [AbstractLibrary.FormBuilder.ReadOnly]
        [Display(Name = "قیمت هر کیلو این نهاده ")]
        [Required]
        public decimal FoodPricePerKg { get; set; }

        [Display(Name = "باقیمانده از این خرید ")]
        [Required]
        public decimal Remain { get; set; }
    }
    
    public class IssueAssignment:SafeDeleteEntity
    {
        public IssueAssignment()
        {
            DateTime = DateTime.Now;
        }

        [Hidden]
        public List<IssueFood> IssueFoods { get; set; }
        
        [Hidden]
        public Distribution Person { get; set; }
        
        [Select]
        [Display(Name = "مشتری ")]
        public long PersonId { get; set; }


        [Text(Help = "کل مبلغی که مشتری می پردازد برای نهاده ای که تحویل می گیرد")]
        [Display(Name = "کل مبلغ ")]
        public decimal TotalPrice { get; set; }

        [Hidden]
        public string BankFish { get; set; }
        
        [TextArea]
        [Display(Name = "توضیحات ")]

        public string Description { get; set; }
        
        [Hidden]
        public DateTime DateTime { get;  set; }

        [NotMapped]
        public string DateTimeIR { get{
            return MyGlobal.ToIranianDateWidthTime(DateTime);
        }  }
    }
}