//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigPardakht.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbstractLibrary.Resource.SharedResource.fa", typeof(SharedResource_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقداری برای خصوصیت &apos;{0}&apos; فراهم نشده است..
        /// </summary>
        internal static string A_value_for_the___0___property_was_not_provided_ {
            get {
                return ResourceManager.GetString("A value for the \'{0}\' property was not provided.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیت پرداخت.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        internal static string BusinessAddress {
            get {
                return ResourceManager.GetString("BusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رپیس کسب و کار .
        /// </summary>
        internal static string BusinessCeoName {
            get {
                return ResourceManager.GetString("BusinessCeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کسب و کار.
        /// </summary>
        internal static string BusinessDomain {
            get {
                return ResourceManager.GetString("BusinessDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی.
        /// </summary>
        internal static string BusinessMiliCode {
            get {
                return ResourceManager.GetString("BusinessMiliCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن کسب وکار.
        /// </summary>
        internal static string BusinessPhone {
            get {
                return ResourceManager.GetString("BusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        internal static string BusinessPostalCode {
            get {
                return ResourceManager.GetString("BusinessPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شماره  .
        /// </summary>
        internal static string BusinessSabtCode {
            get {
                return ResourceManager.GetString("BusinessSabtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع کسب و کار.
        /// </summary>
        internal static string BusinessSubmitDate {
            get {
                return ResourceManager.GetString("BusinessSubmitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه شرکت.
        /// </summary>
        internal static string BusinessUniqId {
            get {
                return ResourceManager.GetString("BusinessUniqId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستندات.
        /// </summary>
        internal static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        internal static string NameAndLastName {
            get {
                return ResourceManager.GetString("NameAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درگاه پرداخت.
        /// </summary>
        internal static string NewPaymentGateway {
            get {
                return ResourceManager.GetString("NewPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد ضروری است.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
