//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigPardakht.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_az_latn_az {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_az_latn_az() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbstractLibrary.Resource.SharedResource.en", typeof(SharedResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقداری برای خصوصیت &apos;{0}&apos; فراهم نشده است..
        /// </summary>
        internal static string A_value_for_the___0___property_was_not_provided_ {
            get {
                return ResourceManager.GetString("A value for the \'{0}\' property was not provided.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن مقدار الزامی است..
        /// </summary>
        internal static string A_value_is_required_ {
            get {
                return ResourceManager.GetString("A value is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Pardakht.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Address.
        /// </summary>
        internal static string BusinessAddress {
            get {
                return ResourceManager.GetString("BusinessAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Ceo Name.
        /// </summary>
        internal static string BusinessCeoName {
            get {
                return ResourceManager.GetString("BusinessCeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        internal static string BusinessDomain {
            get {
                return ResourceManager.GetString("BusinessDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business National Code.
        /// </summary>
        internal static string BusinessMiliCode {
            get {
                return ResourceManager.GetString("BusinessMiliCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Phone.
        /// </summary>
        internal static string BusinessPhone {
            get {
                return ResourceManager.GetString("BusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Postal Code.
        /// </summary>
        internal static string BusinessPostalCode {
            get {
                return ResourceManager.GetString("BusinessPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Code.
        /// </summary>
        internal static string BusinessSabtCode {
            get {
                return ResourceManager.GetString("BusinessSabtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Start Date.
        /// </summary>
        internal static string BusinessSubmitDate {
            get {
                return ResourceManager.GetString("BusinessSubmitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unique Id.
        /// </summary>
        internal static string BusinessUniqId {
            get {
                return ResourceManager.GetString("BusinessUniqId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        internal static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name And LastName.
        /// </summary>
        internal static string NameAndLastName {
            get {
                return ResourceManager.GetString("NameAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Payment Gateway.
        /// </summary>
        internal static string NewPaymentGateway {
            get {
                return ResourceManager.GetString("NewPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار خالی معتبر نیست..
        /// </summary>
        internal static string Null_value_is_invalid_ {
            get {
                return ResourceManager.GetString("Null value is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this field is Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد &apos;{0}&apos; بایستی عددی باشد..
        /// </summary>
        internal static string The_field__0__must_be_a_number_ {
            get {
                return ResourceManager.GetString("The field {0} must be a number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای {0} معتبر نیست..
        /// </summary>
        internal static string The_supplied_value_is_invalid_for__0__ {
            get {
                return ResourceManager.GetString("The supplied value is invalid for {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار &apos;{0}&apos; معتبر نیست..
        /// </summary>
        internal static string The_value___0___is_invalid_ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار &apos;{0}&apos; برای {1} معتبر نیست..
        /// </summary>
        internal static string The_value___0___is_not_valid_for__1__ {
            get {
                return ResourceManager.GetString("The value \'{0}\' is not valid for {1}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
